# generated by aind-data-schema-models:
#     filename:  https://raw.githubusercontent.com/harp-tech/protocol/97ded281bd1d0d7537f90ebf545d74cf8ba8805e/whoami.yml
#     timestamp: 2024-10-10 19:32:56.101024+00:00

from typing import Annotated, Literal, Union

from pydantic import Field, RootModel

from aind_data_schema_models._generators._base import _HarpDeviceTypeModel


class Behavior(_HarpDeviceTypeModel):

    name: Literal["Behavior"] = "Behavior"
    whoami: Literal[1216] = 1216


class CameraController(_HarpDeviceTypeModel):

    name: Literal["Camera Controller"] = "Camera Controller"
    whoami: Literal[1168] = 1168


class ClockSynchronizer(_HarpDeviceTypeModel):

    name: Literal["Clock Synchronizer"] = "Clock Synchronizer"
    whoami: Literal[1152] = 1152


class Cuttlefish(_HarpDeviceTypeModel):

    name: Literal["Cuttlefish"] = "Cuttlefish"
    whoami: Literal[1403] = 1403


class GenericHarpDevice(_HarpDeviceTypeModel):

    name: Literal["Generic Harp Device"] = "Generic Harp Device"
    whoami: Literal[0] = 0


class InputExpander(_HarpDeviceTypeModel):

    name: Literal["Input Expander"] = "Input Expander"
    whoami: Literal[1106] = 1106


class LicketySplit(_HarpDeviceTypeModel):

    name: Literal["Lickety Split"] = "Lickety Split"
    whoami: Literal[1400] = 1400


class LoadCells(_HarpDeviceTypeModel):

    name: Literal["Load Cells"] = "Load Cells"
    whoami: Literal[1232] = 1232


class Olfactometer(_HarpDeviceTypeModel):

    name: Literal["Olfactometer"] = "Olfactometer"
    whoami: Literal[1140] = 1140


class SniffDetector(_HarpDeviceTypeModel):

    name: Literal["Sniff Detector"] = "Sniff Detector"
    whoami: Literal[1401] = 1401


class SoundCard(_HarpDeviceTypeModel):

    name: Literal["Sound Card"] = "Sound Card"
    whoami: Literal[1280] = 1280


class StepperDriver(_HarpDeviceTypeModel):

    name: Literal["Stepper Driver"] = "Stepper Driver"
    whoami: Literal[1130] = 1130


class Synchronizer(_HarpDeviceTypeModel):

    name: Literal["Synchronizer"] = "Synchronizer"
    whoami: Literal[1104] = 1104


class TimestampGeneratorGen1(_HarpDeviceTypeModel):

    name: Literal["Timestamp Generator Gen 1"] = "Timestamp Generator Gen 1"
    whoami: Literal[1154] = 1154


class TimestampGeneratorGen3(_HarpDeviceTypeModel):

    name: Literal["Timestamp Generator Gen 3"] = "Timestamp Generator Gen 3"
    whoami: Literal[1158] = 1158


class Treadmill(_HarpDeviceTypeModel):

    name: Literal["Treadmill"] = "Treadmill"
    whoami: Literal[1402] = 1402


class _HarpDeviceType:

    BEHAVIOR = Behavior()
    CAMERA_CONTROLLER = CameraController()
    CLOCK_SYNCHRONIZER = ClockSynchronizer()
    CUTTLEFISH = Cuttlefish()
    GENERIC_HARP_DEVICE = GenericHarpDevice()
    INPUT_EXPANDER = InputExpander()
    LICKETY_SPLIT = LicketySplit()
    LOAD_CELLS = LoadCells()
    OLFACTOMETER = Olfactometer()
    SNIFF_DETECTOR = SniffDetector()
    SOUND_CARD = SoundCard()
    STEPPER_DRIVER = StepperDriver()
    SYNCHRONIZER = Synchronizer()
    TIMESTAMP_GENERATOR_GEN_1 = TimestampGeneratorGen1()
    TIMESTAMP_GENERATOR_GEN_3 = TimestampGeneratorGen3()
    TREADMILL = Treadmill()

    ALL = tuple(_HarpDeviceTypeModel.__subclasses__())

    class ONE_OF(RootModel):
        root: Annotated[
            Union[tuple(_HarpDeviceTypeModel.__subclasses__())],
            Field(discriminator="name"),
        ]
